import { useState, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { Search, Shield, BookOpen, AlertCircle, Loader2 } from 'lucide-react';
import { askQuestion } from './services/api';
import type { QueryResponse } from './types';
import SourcePill from './components/SourcePill';
import ExamplePrompts from './components/ExamplePrompts';

type Status = 'idle' | 'loading' | 'success' | 'error';

export default function App() {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<Status>('idle');
  const [result, setResult] = useState<QueryResponse | null>(null);
  const [errorMsg, setErrorMsg] = useState('');
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  async function handleSubmit(q: string = query) {
    const trimmed = q.trim();
    if (!trimmed) return;

    setStatus('loading');
    setResult(null);
    setErrorMsg('');

    try {
      const data = await askQuestion(trimmed);
      setResult(data);
      setStatus('success');
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : 'An unexpected error occurred.');
      setStatus('error');
    }
  }

  function handleExampleSelect(prompt: string) {
    setQuery(prompt);
    textareaRef.current?.focus();
    handleSubmit(prompt);
  }

  return (
    <div className="min-h-screen bg-aws-squid">
      {/* Header */}
      <header className="border-b border-aws-border bg-[#161b22]">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center gap-3">
          <Shield className="text-aws-orange" size={28} />
          <div>
            <h1 className="text-lg font-bold text-aws-text leading-tight">AI Agent Insure</h1>
            <p className="text-xs text-aws-muted">Knowledge Assistant · Amazon Bedrock RAG + S3 Vectors</p>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-10">
        {/* Intro */}
        <div className="mb-8 flex items-start gap-3">
          <BookOpen className="text-aws-orange mt-0.5 shrink-0" size={20} />
          <p className="text-aws-muted text-sm leading-relaxed">
            Ask any question about AI Agent Insure products, coverage, or policies. Answers are
            generated by <strong className="text-aws-text">Amazon Bedrock</strong> using
            Retrieval-Augmented Generation (RAG) backed by an{' '}
            <strong className="text-aws-text">S3 Vectors</strong> knowledge base.
          </p>
        </div>

        {/* Query input */}
        <div className="bg-aws-ink border border-aws-border rounded-lg p-5">
          <label htmlFor="query" className="block text-xs uppercase tracking-widest text-aws-muted font-semibold mb-2">
            Your question
          </label>
          <textarea
            id="query"
            ref={textareaRef}
            rows={3}
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) handleSubmit();
            }}
            placeholder="e.g. What does Agentic AI Liability Insurance cover?"
            className="w-full bg-aws-squid border border-aws-border rounded-md px-4 py-3 text-aws-text placeholder-aws-muted text-sm resize-none focus:outline-none focus:border-aws-orange transition-colors"
          />
          <div className="mt-3 flex items-center justify-between">
            <span className="text-xs text-aws-muted">⌘ + Enter to submit</span>
            <button
              onClick={() => handleSubmit()}
              disabled={status === 'loading' || !query.trim()}
              className="flex items-center gap-2 bg-aws-orange hover:bg-aws-orange-dark disabled:opacity-40 disabled:cursor-not-allowed text-[#0d1117] font-bold text-sm px-5 py-2 rounded-md transition-colors"
            >
              {status === 'loading' ? (
                <Loader2 size={16} className="animate-spin" />
              ) : (
                <Search size={16} />
              )}
              {status === 'loading' ? 'Searching…' : 'Ask'}
            </button>
          </div>
        </div>

        {/* Example prompts — shown when idle */}
        {status === 'idle' && (
          <ExamplePrompts onSelect={handleExampleSelect} />
        )}

        {/* Error */}
        {status === 'error' && (
          <div className="mt-6 flex items-start gap-3 bg-red-950 border border-red-800 rounded-lg px-5 py-4">
            <AlertCircle className="text-red-400 shrink-0 mt-0.5" size={18} />
            <div>
              <p className="text-red-300 font-semibold text-sm">Request failed</p>
              <p className="text-red-400 text-sm mt-0.5">{errorMsg}</p>
            </div>
          </div>
        )}

        {/* Result */}
        {status === 'success' && result && (
          <div className="mt-6 space-y-4">
            {/* Answer */}
            <div className="bg-aws-ink border-l-4 border-aws-orange rounded-lg px-6 py-5">
              <p className="text-xs uppercase tracking-widest text-aws-orange font-semibold mb-3">
                Answer
              </p>
              <div className="prose prose-invert prose-sm max-w-none text-aws-text leading-relaxed">
                <ReactMarkdown>{result.generated_response}</ReactMarkdown>
              </div>
            </div>

            {/* Sources */}
            {result.s3_locations.length > 0 && (
              <div className="bg-aws-card border border-aws-border rounded-lg px-6 py-4">
                <p className="text-xs uppercase tracking-widest text-aws-muted font-semibold mb-3">
                  Sources retrieved from knowledge base
                </p>
                <div className="flex flex-wrap">
                  {result.s3_locations.map((uri) => (
                    <SourcePill key={uri} uri={uri} />
                  ))}
                </div>
              </div>
            )}

            {/* Ask another */}
            <ExamplePrompts onSelect={handleExampleSelect} />
          </div>
        )}
      </main>
    </div>
  );
}
